# Generated by Django 5.2.3 on 2025-06-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_codeflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castmember',
            options={'ordering': ['name']},
        ),
    ]
