# Generated by Django 5.2.3 on 2025-06-26 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_codeflix', '0002_alter_castmember_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='genres', to='desafio_codeflix.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('year_launched', models.IntegerField()),
                ('opened', models.BooleanField(default=False)),
                ('rating', models.CharField(choices=[('L', 'L'), ('AGE_10', '10'), ('AGE_12', '12'), ('AGE_14', '14'), ('AGE_16', '16'), ('AGE_18', '18')], max_length=10)),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast_members', models.ManyToManyField(related_name='videos', to='desafio_codeflix.castmember')),
                ('categories', models.ManyToManyField(related_name='videos', to='desafio_codeflix.category')),
                ('genres', models.ManyToManyField(related_name='videos', to='desafio_codeflix.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
